### ISSUE TITLE
It dos not work YouTube adway

### ISSUE THREAD

**Issue by Bryanx999** [wanam/YouTubeAdAway#104]
Registro
09-22 15:29:27.792 I/Xposed  (  672): -----------------
09-22 15:29:27.792 I/Xposed  (  672): Starting Xposed version 89, compiled for SDK 22
09-22 15:29:27.792 I/Xposed  (  672): Device: C6902 (Sony), Android version 5.1.1 (SDK 22)
09-22 15:29:27.792 I/Xposed  (  672): ROM: 14.6.A.1.236
09-22 15:29:27.792 I/Xposed  (  672): Build fingerprint: Sony/C6902/C6902:5.1.1/14.6.A.1.236/2031203603:user/release-keys
09-22 15:29:27.792 I/Xposed  (  672): Platform: armeabi-v7a, 32-bit binary, system server: yes
09-22 15:29:27.793 I/Xposed  (  672): SELinux enabled: yes, enforcing: no
09-22 15:29:30.397 I/Xposed  (  672): -----------------
09-22 15:29:30.398 I/Xposed  (  672): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-22 15:29:30.919 I/Xposed  (  672): Detected ART runtime
09-22 15:29:30.942 I/Xposed  (  672): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-22 15:29:31.441 I/Xposed  (  672): Loading modules from /data/app/serajr.xx.lp-1/base.apk
09-22 15:29:31.472 I/Xposed  (  672):   Loading class serajr.xx.lp.Xposed
09-22 15:29:31.535 I/Xposed  (  672): Loading modules from /data/app/com.smartmadsoft.xposed.obbonsd-1/base.apk
09-22 15:29:31.573 I/Xposed  (  672):   Loading class com.smartmadsoft.xposed.obbonsd.Relocator
09-22 15:29:31.594 I/Xposed  (  672): Loading modules from /data/app/com.zst.xposed.screenoffanimation-1/base.apk
09-22 15:29:32.687 I/Xposed  (  672):   Loading class com.zst.xposed.screenoffanimation.MainXposed
09-22 15:29:32.719 I/Xposed  (  672): Loading modules from /data/app/tw.fatminmin.xposed.minminguard-1/base.apk
09-22 15:29:32.754 I/Xposed  (  672):   Loading class tw.fatminmin.xposed.minminguard.Main
09-22 15:29:32.936 I/Xposed  (  672): Loading modules from /data/app/com.aviraxp.adblocker.continued-1/base.apk
09-22 15:29:32.936 E/Xposed  (  672):   File does not exist
09-22 15:29:32.936 I/Xposed  (  672): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
09-22 15:29:32.952 I/Xposed  (  672):   Loading class ma.wanam.youtubeadaway.Xposed
09-22 15:29:32.959 I/Xposed  (  672): Loading modules from /data/app/zzzz.zzzz.youtubeadkiller-1/base.apk
09-22 15:29:32.992 I/Xposed  (  672):   Loading class zzzz.zzzz.youtubeadkiller.MainHook
09-22 15:29:33.022 I/Xposed  (  672): Loading modules from /data/app/com.dym.motoxtether-1/base.apk
09-22 15:29:33.028 I/Xposed  (  672):   Loading class com.dym.motoxtether.BreakTether
09-22 15:29:35.101 E/Xposed  ( 1516): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.PowerManagerService
09-22 15:29:35.101 E/Xposed  ( 1516): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at com.zst.xposed.screenoffanimation.MainXposed.handleLoadPackage(MainXposed.java:75)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at de.robv.android.xposed.XposedInit$4$1.beforeHookedMethod(XposedInit.java:176)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at com.android.server.SystemServer.startBootstrapServices(<Xposed>)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at com.android.server.SystemServer.run(SystemServer.java:267)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at com.android.server.SystemServer.main(SystemServer.java:183)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at java.lang.reflect.Method.invoke(Native Method)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at java.lang.reflect.Method.invoke(Method.java:372)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
09-22 15:29:35.101 E/Xposed  ( 1516): Caused by: java.lang.ClassNotFoundException: com.android.server.PowerManagerService
09-22 15:29:35.101 E/Xposed  ( 1516): 	at java.lang.Class.classForName(Native Method)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at java.lang.Class.forName(Class.java:309)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
09-22 15:29:35.101 E/Xposed  ( 1516): 	... 14 more
09-22 15:29:35.101 E/Xposed  ( 1516): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.server.PowerManagerService" on path: DexPathList[[zip file "/system/framework/services.jar", zip file "/system/framework/ethernet-service.jar", zip file "/system/framework/wifi-service.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
09-22 15:29:35.101 E/Xposed  ( 1516): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-22 15:29:35.101 E/Xposed  ( 1516): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
09-22 15:29:35.101 E/Xposed  ( 1516): 	... 18 more
09-22 15:29:35.101 E/Xposed  ( 1516): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.android.server.PowerManagerService" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
09-22 15:29:35.101 E/Xposed  ( 1516): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-22 15:29:35.101 E/Xposed  ( 1516): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-22 15:29:35.101 E/Xposed  ( 1516): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-22 15:29:35.101 E/Xposed  ( 1516): 		... 19 more
09-22 15:29:35.101 E/Xposed  ( 1516): 		Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.android.server.PowerManagerService" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex", dex file "/data/dalvik-cache/xposed_XTypedArraySuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
09-22 15:29:35.101 E/Xposed  ( 1516): 			at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-22 15:29:35.101 E/Xposed  ( 1516): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-22 15:29:35.101 E/Xposed  ( 1516): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-22 15:29:35.101 E/Xposed  ( 1516): 			... 20 more
09-22 15:29:35.101 E/Xposed  ( 1516): 			Suppressed: java.lang.ClassNotFoundException: com.android.server.PowerManagerService
09-22 15:29:35.101 E/Xposed  ( 1516): 				at java.lang.Class.classForName(Native Method)
09-22 15:29:35.101 E/Xposed  ( 1516): 				at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
09-22 15:29:35.101 E/Xposed  ( 1516): 				at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
09-22 15:29:35.101 E/Xposed  ( 1516): 				at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-22 15:29:35.101 E/Xposed  ( 1516): 				... 21 more
09-22 15:29:35.101 E/Xposed  ( 1516): 			Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
09-22 15:30:06.099 E/Xposed  ( 1731): java.lang.NoSuchMethodError: com.sonymobile.home.DisplayData#updateConfiguration(android.content.res.Resources,android.view.Display)#exact
09-22 15:30:06.099 E/Xposed  ( 1731): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at serajr.xx.lp.hooks.home.Home_DisplayDataCommon.hook(Home_DisplayDataCommon.java:31)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at serajr.xx.lp.Xposed.handleLoadPackage(Xposed.java:192)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at android.app.ActivityThread.access$1500(ActivityThread.java:156)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at android.os.Looper.loop(Looper.java:211)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at android.app.ActivityThread.main(ActivityThread.java:5389)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at java.lang.reflect.Method.invoke(Native Method)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at java.lang.reflect.Method.invoke(Method.java:372)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
09-22 15:30:06.099 E/Xposed  ( 1731): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
09-22 15:30:58.462 I/XposedInstaller( 3776): RepoLoader -> Downloaded http://dl.xposed.info/repo/partial/15864.xml.gz with status 0 (error: null), size 66 bytes
09-22 15:30:58.506 I/XposedInstaller( 3776): RepoLoader -> Updated repository http://dl.xposed.info/repo/full.xml.gz to version 15864 (0 new / 0 removed modules)
09-22 15:32:21.293 I/Xposed  ( 8415): YouTube: com.google.android.youtube 13.37.52 loaded with module version 4.3.3
09-22 16:24:23.420 I/Xposed  (25554): YouTube: com.google.android.youtube 13.37.52 loaded with module version 4.3.3
09-22 16:38:46.272 I/Xposed  (28141): YouTube: com.google.android.youtube 13.37.52 loaded with module version 4.3.3
09-22 16:57:02.470 I/XposedInstaller( 5259): RepoLoader -> Downloaded http://dl.xposed.info/repo/partial/15864.xml.gz with status 0 (error: null), size 66 bytes
09-22 16:57:02.480 I/XposedInstaller( 5259): RepoLoader -> Updated repository http://dl.xposed.info/repo/full.xml.gz to version 15864 (0 new / 0 removed modules)
09-22 16:58:41.174 I/XposedInstaller( 5259): RepoLoader -> Downloaded http://dl.xposed.info/repo/partial/15864.xml.gz with status 0 (error: null), size 66 bytes
09-22 16:58:41.177 I/XposedInstaller( 5259): RepoLoader -> Updated repository http://dl.xposed.info/repo/full.xml.gz to version 15864 (0 new / 0 removed modules)
09-22 16:59:24.589 I/XposedInstaller( 5259): RepoLoader -> Downloaded http://dl.xposed.info/repo/partial/15864.xml.gz with status 0 (error: null), size 66 bytes
09-22 16:59:24.593 I/XposedInstaller( 5259): RepoLoader -> Updated repository http://dl.xposed.info/repo/full.xml.gz to version 15864 (0 new / 0 removed modules)
09-22 17:39:59.467 I/Xposed  (15253): YouTube: com.google.android.youtube 13.37.52 loaded with module version 4.3.3
09-22 18:15:45.564 I/Xposed  (20355): YouTube: com.google.android.youtube 13.37.52 loaded with module version 4.3.3
09-22 19:43:36.965 I/Xposed  (30364): YouTube: com.google.android.youtube 13.37.52 loaded with module version 4.3.3
09-22 20:16:28.359 I/Xposed  (19502): YouTube: com.google.android.youtube 13.37.52 loaded with module version 4.3.3
09-22 20:16:42.261 I/XposedInstaller(19669): RepoLoader -> Downloaded http://dl.xposed.info/repo/partial/15864.xml.gz with status 0 (error: null), size 66 bytes
09-22 20:16:42.272 I/XposedInstaller(19669): RepoLoader -> Updated repository http://dl.xposed.info/repo/full.xml.gz to version 15864 (0 new / 0 removed modules)

**Comment by SandPox** [comment]
https://github.com/wanam/YouTubeAdAway/pull/94
