### ISSUE TITLE
Force close

### ISSUE THREAD

**Issue by Guerrer0** [wanam/YouTubeAdAway#167]
``java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(Unknown Source:27)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: nGEso.FAiBw.qOrZYWm.MG.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity
	at nGEso.FAiBw.qOrZYWm.MG.XposedHelpers.findClass(Unknown Source:12)
	at nGEso.FAiBw.qOrZYWm.MG.XposedHelpers.findAndHookMethod(SourceFile:2)
	at ma.wanam.youtubeadaway.BFAsync.doInBackground(BFAsync.java:77)
	at ma.wanam.youtubeadaway.BFAsync.doInBackground(BFAsync.java:27)
	at android.os.AsyncTask$3.call(Unknown Source:20)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more
Caused by: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at q.a(Unknown Source:16)
	at nGEso.FAiBw.qOrZYWm.MG.XposedHelpers.findClass(Unknown Source:4)
	... 9 more
Caused by: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity
	... 13 more

**Comment by AllenChangMusic** [comment]
I can second this. Broken with newest update!

**Comment by DTK0kai** [comment]
Ok so I'm not the only one who's youtube app flat out crashes all of the sudden. Had to downgrade YouTube just to get the app to open. I figured it was this plugin as it happend before.

**Comment by dekefake** [comment]
I can confirm this is happening here as well. YouTube AdAway will need an update 🙃

**Comment by wanam** [comment]
It seems a big change since the impacted class is not proguarded, you can disable "ad cards hide" in the meantime.
I will check when I have time...

**Comment by dekefake** [comment]
Sure take your time.

FYI I tried to enable and disable all features one by one and it always makes YouTube crashes. Disabling the module allows the apps to load.

**Comment by kaedea** [comment]
Rollbacking to [18.46.43](https://m.apkpure.com/youtube/com.google.android.youtube/download/18.46.43) may help.
