### ISSUE TITLE
Latest YouTube crashed 

### ISSUE THREAD

**Issue by mashunterbd** [wanam/YouTubeAdAway#172]
Not being able to use the latest version of YouTube keeps crashing. YouTube cannot be used in any way after activating this module.Please fix it

**Comment by mashunterbd** [comment]
Logs: 

[ 2024-02-07T09:58:07.111    10630: 15400: 15400 I/LSPosed-Bridge  ] Loading legacy module ma.wanam.youtubeadaway from /data/app/~~N4ej6GT3TLBCkaEvD8UKyg==/ma.wanam.youtubeadaway-C2gAqfWd_RAybWE4L831Mw==/base.apk
[ 2024-02-07T09:58:07.173    10630: 15400: 15400 I/LSPosed-Bridge  ]   Loading class ma.wanam.youtubeadaway.Xposed
[ 2024-02-07T09:58:07.190    10630: 15400: 15400 I/LSPosed-Bridge  ] Loading legacy module ru.mike.updatelocker from /data/app/~~UIjRlFDawrROjEr_Cpwo3w==/ru.mike.updatelocker--Pic9fVBEOWKf-Z_gRVnSA==/base.apk
[ 2024-02-07T09:58:07.199    10630: 15400: 15400 I/LSPosed-Bridge  ]   Loading class ru.mike.updatelocker.XposedMod
[ 2024-02-07T09:58:07.476    10630: 15400: 15400 I/LSPosed-Bridge  ] Hooking YouTube version: com.google.android.youtube 1544281536
[ 2024-02-07T09:58:07.489    10630: 15400: 15434 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: a.gaYms.N.YdLII.ukyUrQ.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity
	at a.gaYms.N.YdLII.ukyUrQ.XposedHelpers.findClass(Unknown Source:12)
	at a.gaYms.N.YdLII.ukyUrQ.XposedHelpers.findAndHookMethod(SourceFile:6)
	at ma.wanam.youtubeadaway.BFAsync.doInBackground(BFAsync.java:77)
	at ma.wanam.youtubeadaway.BFAsync.doInBackground(BFAsync.java:27)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more
Caused by: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at q.a(Unknown Source:16)
	at a.gaYms.N.YdLII.ukyUrQ.XposedHelpers.findClass(Unknown Source:4)
	... 9 more
Caused by: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity
	... 13 more
[ 2024-02-07T09:58:08.157    10138: 15503: 15503 I/LSPosed-Bridge  ] Loading legacy module com.android1500.gpssetter from /data/app/~~1uOJz8Po7LIPR6zyqzNhqQ==/com.android1500.gpssetter-_mHKCbWgWeVNsYE1i_7Byw==/base.apk
[ 2024-02-07T09:58:08.231    10138: 15503: 15503 I/LSPosed-Bridge  ]   Loading class com.android1500.gpssetter.xposed.XposedHook
[ 2024-02-07T09:58:08.591    10138: 15530: 15530 I/LSPosed-Bridge  ] Loading legacy module com.android1500.gpssetter from /data/app/~~1uOJz8Po7LIPR6zyqzNhqQ==/com.android1500.gpssetter-_mHKCbWgWeVNsYE1i_7Byw==/base.apk
[ 2024-02-07T09:58:08.749    10138: 15530: 15530 I/LSPosed-Bridge  ]   Loading class com.android1500.gpssetter.xposed.XposedHook
[ 2024-02-07T09:58:23.474     1000: 15635: 15635 I/LSPosed-Bridge  ] Loading legacy module name.monwf.customiuizer from /data/app/~~gaDqEE7-jWFOI96WvDKppA==/name.monwf.customiuizer-gDnENMNSPDSlUwXaO26-nw==/base.apk
[ 2024-02-07T09:58:23.490     1000: 15635: 15635 I/LSPosed-Bridge  ]   Loading class name.mikanoshi.customiuizer.MainModule
[ 2024-02-07T09:58:23.507     1000: 15635: 15635 I/LSPosed-Bridge  ] Loading legacy module chili.xposed.chimi from /data/app/~~ttqm3m-VSqUjQVINRJQatw==/chili.xposed.chimi-1zsv1kEwFav4uF6XU_KK7g==/base.apk
[ 2024-02-07T09:58:23.526     1000: 15635: 15635 I/LSPosed-Bridge  ]   Loading class chili.xposed.chimi.hooks.HookEntry
[ 2024-02-07T09:58:23.744     1000: 15635: 15635 I/LSPosed-Bridge  ] [CustoMIUIzer][UnlockClipboardAndLocationHook] Failed to hook onCreateFragment method in com.miui.permcenter.settings.PrivacyLabActivity
[ 2024-02-07T09:58:23.745     1000: 15635: 15635 I/LSPosed-Bridge  ] [CustoMIUIzer][AddSideBarExpandReceiverHook] failed to find RegionSamplingHelper
[ 2024-02-07T09:58:23.745     1000: 15635: 15635 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.reflect.Constructor[] java.lang.Class.getDeclaredConstructors()' on a null object reference
	at a.gaYms.N.YdLII.ukyUrQ.XposedBridge.hookAllConstructors(Unknown Source:5)
	at name.mikanoshi.customiuizer.utils.Helpers.hookAllConstructors(Helpers.java:5)
	at name.mikanoshi.customiuizer.mods.Various.AddSideBarExpandReceiverHook(Various.java:59)
	at name.mikanoshi.customiuizer.MainModule.handleLoadPackage(MainModule.java:3588)
	at a.gaYms.N.YdLII.ukyUrQ.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at a.gaYms.N.YdLII.ukyUrQ.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at a.gaYms.N.YdLII.ukyUrQ.callbacks.XCallback.callAll(Unknown Source:26)
	at g0.a(Unknown Source:285)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:253)
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1072)
	at android.app.LoadedApk.getResources(LoadedApk.java:1320)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3025)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3017)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6978)
	at android.app.ActivityThread.access$1600(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
[ 2024-02-07T09:58:23.746     1000: 15635: 15635 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getCanonicalName()' on a null object reference
	at name.mikanoshi.customiuizer.utils.Helpers.findAndHookMethod(Helpers.java:4)
	at name.mikanoshi.customiuizer.mods.Various.AddSideBarExpandReceiverHook(Various.java:79)
	at name.mikanoshi.customiuizer.MainModule.handleLoadPackage(MainModule.java:3588)
	at a.gaYms.N.YdLII.ukyUrQ.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at a.gaYms.N.YdLII.ukyUrQ.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at a.gaYms.N.YdLII.ukyUrQ.callbacks.XCallback.callAll(Unknown Source:26)
	at g0.a(Unknown Source:285)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:253)
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1072)
	at android.app.LoadedApk.getResources(LoadedApk.java:1320)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3025)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3017)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6978)
	at android.app.ActivityThread.access$1600(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
[ 2024-02-07T09:58:41.815    10630: 16406: 16406 I/LSPosed-Bridge  ] Loading legacy module ma.wanam.youtubeadaway from /data/app/~~N4ej6GT3TLBCkaEvD8UKyg==/ma.wanam.youtubeadaway-C2gAqfWd_RAybWE4L831Mw==/base.apk
[ 2024-02-07T09:58:41.845    10630: 16406: 16406 I/LSPosed-Bridge  ]   Loading class ma.wanam.youtubeadaway.Xposed
[ 2024-02-07T09:58:41.852    10630: 16406: 16406 I/LSPosed-Bridge  ] Loading legacy module ru.mike.updatelocker from /data/app/~~UIjRlFDawrROjEr_Cpwo3w==/ru.mike.updatelocker--Pic9fVBEOWKf-Z_gRVnSA==/base.apk
[ 2024-02-07T09:58:41.862    10630: 16406: 16406 I/LSPosed-Bridge  ]   Loading class ru.mike.updatelocker.XposedMod
[ 2024-02-07T09:58:42.045    10630: 16406: 16406 I/LSPosed-Bridge  ] Hooking YouTube version: com.google.android.youtube 1544281536
[ 2024-02-07T09:58:42.056    10630: 16406: 16444 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: a.gaYms.N.YdLII.ukyUrQ.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity
	at a.gaYms.N.YdLII.ukyUrQ.XposedHelpers.findClass(Unknown Source:12)
	at a.gaYms.N.YdLII.ukyUrQ.XposedHelpers.findAndHookMethod(SourceFile:6)
	at ma.wanam.youtubeadaway.BFAsync.doInBackground(BFAsync.java:77)
	at ma.wanam.youtubeadaway.BFAsync.doInBackground(BFAsync.java:27)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more
Caused by: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at q.a(Unknown Source:16)
	at a.gaYms.N.YdLII.ukyUrQ.XposedHelpers.findClass(Unknown Source:4)
	... 9 more
Caused by: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity
	... 13 more
[ 2024-02-07T09:58:50.827     1000: 16995: 16995 I/LSPosed-Bridge  ] Loading legacy module com.android1500.gpssetter from /data/app/~~1uOJz8Po7LIPR6zyqzNhqQ==/com.android1500.gpssetter-_mHKCbWgWeVNsYE1i_7Byw==/base.apk
[ 2024-02-07T09:58:50.899     1000: 16995: 16995 I/LSPosed-Bridge  ]   Loading class com.android1500.gpssetter.xposed.XposedHook
[ 2024-02-07T09:58:53.161    10630: 17091: 17091 I/LSPosed-Bridge  ] Loading legacy module ma.wanam.youtubeadaway from /data/app/~~N4ej6GT3TLBCkaEvD8UKyg==/ma.wanam.youtubeadaway-C2gAqfWd_RAybWE4L831Mw==/base.apk
[ 2024-02-07T09:58:53.248    10630: 17091: 17091 I/LSPosed-Bridge  ]   Loading class ma.wanam.youtubeadaway.Xposed
[ 2024-02-07T09:58:53.270    10630: 17091: 17091 I/LSPosed-Bridge  ] Loading legacy module ru.mike.updatelocker from /data/app/~~UIjRlFDawrROjEr_Cpwo3w==/ru.mike.updatelocker--Pic9fVBEOWKf-Z_gRVnSA==/base.apk
[ 2024-02-07T09:58:53.291    10630: 17091: 17091 I/LSPosed-Bridge  ]   Loading class ru.mike.updatelocker.XposedMod
[ 2024-02-07T09:58:53.528    10630: 17091: 17091 I/LSPosed-Bridge  ] Hooking YouTube version: com.google.android.youtube 1544281536
[ 2024-02-07T09:58:53.539    10630: 17091: 17127 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: a.gaYms.N.YdLII.ukyUrQ.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity
	at a.gaYms.N.YdLII.ukyUrQ.XposedHelpers.findClass(Unknown Source:12)
	at a.gaYms.N.YdLII.ukyUrQ.XposedHelpers.findAndHookMethod(SourceFile:6)
	at ma.wanam.youtubeadaway.BFAsync.doInBackground(BFAsync.java:77)
	at ma.wanam.youtubeadaway.BFAsync.doInBackground(BFAsync.java:27)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more
