### ISSUE TITLE
Youtube Keeps Crashing

### ISSUE THREAD

**Issue by malitech** [wanam/YouTubeAdAway#60]
Tried reinstalling youtube and adaway module but keeps crashing.
Pixel Experience 8.1 rom
Redmi note 4
Magisk
[error.log](https://github.com/wanam/YouTubeAdAway/files/1721415/error.log)

**Comment by wanam** [comment]
> Abort message: 'quick_exception_handler.cc:326] Check failed: callee_method_ != nullptr de.robv.android.xposed.XposedBridge.hookAllConstructors'

It's an [Xposed bug on Oreo Roms](https://github.com/rovo89/Xposed/issues/325).

**Comment by malitech** [comment]
Do I need to report it in xposed page?

**Comment by wanam** [comment]
No, it's already reported and rovo89 is aware of it.

**Comment by malitech** [comment]
Thank you!

**Comment by msmilkshake** [comment]
I double this. YouTube FC to me too with the new Xposed for Oreo 8.1

**Comment by ZaneCEO** [comment]
Found this Googling for the same problem. Just want to say thanks @malitech for reporting it.

**Comment by L0laapk3** [comment]
Is there any workaround/Known version that does not suffer from this problem? It makes the app effectively unusable.

**Comment by Sethur** [comment]
I'm on Marshmallow (6.0.1) and get the crashes as well. Clearing the app data/cache will fix this for a short amount of time but the crashes come back after a few minutes. I tried downgrading to 13.12.60 and it seems to have worked.

**Comment by keatonthewise** [comment]
I just started experiencing crashes with YouTube 13.12.60 (albeit not as often as with later versions), so I kept reverting back until I hit 13.07.55. No crashes so far.

**Comment by wanam** [comment]
@keatonthewise @Sethur please post your logcat so i can make sure we are talking about the same issue.

**Comment by keatonthewise** [comment]
05-23 18:47:39.528 W/YouTube (2490): Fetching the Gservices key 'failsafe_clear_cache_release_13_02' before the end of the bulk initialization
05-23 18:47:39.563 W/YouTube (2490): Fetching the Gservices key 'disable_binder_callback_flush' before the end of the bulk initialization
05-23 18:47:39.589 W/YouTube (2490): Fetching the Gservices key 'disable_native_cronet' before the end of the bulk initialization
05-23 18:47:41.001 E/YouTube (2490): InteractionLoggingScreen is null.
05-23 18:47:41.067 E/YouTube (2490): InteractionLoggingScreen is null.
05-23 18:47:41.383 E/YouTube (2490): InteractionLoggingScreen is null.
05-23 18:47:41.384 E/YouTube (2490): InteractionLoggingScreen is null.
05-23 18:47:41.390 W/YouTube (2490): Suppressed bad viewport dimensions. Video quality may suffer!
05-23 18:47:41.390 W/YouTube (2490): Suppressed bad viewport dimensions. Video quality may suffer!
05-23 18:47:41.422 E/YouTube (2490): InteractionLoggingScreen is null.
05-23 18:47:41.422 E/YouTube (2490): InteractionLoggingScreen is null.
05-23 18:47:41.845 W/Tesla.OEMBroadcast(28897): onReceive: android.intent.action.BADGE_COUNT_UPDATE ComponentTag{com.google.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity} 0
05-23 18:47:41.903 W/Tesla.OEMBroadcast(28897): onReceive: android.intent.action.BADGE_COUNT_UPDATE ComponentTag{com.google.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity} 0
05-23 18:47:42.719 E/AndroidRuntime(2490): Process: com.google.android.youtube, PID: 2490
05-23 18:47:42.719 E/AndroidRuntime(2490): 	at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback$HooksDownloadTask.doInBackground(YouTubeBackgroundPlayback.java:266)
05-23 18:47:42.719 E/AndroidRuntime(2490): 	at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback$HooksDownloadTask.doInBackground(YouTubeBackgroundPlayback.java:253)
05-23 18:47:42.723 W/ActivityManager(3982):   Force finishing activity com.google.android.youtube/com.google.android.apps.youtube.app.WatchWhileActivity
05-23 18:47:42.925 W/PkgUtils(28672): p: com.google.android.youtube, u:0
05-23 18:47:42.982 W/PkgUtils(29185): p: com.google.android.youtube, u:0
05-23 18:47:43.449 W/YouTube (2490): CsiAction [dfb] already ticked pl_int. Ignored.
05-23 18:47:44.256 W/YouTube (2733): Fetching the Gservices key 'failsafe_clear_cache_release_13_02' before the end of the bulk initialization
05-23 18:47:44.276 W/YouTube (2733): Fetching the Gservices key 'disable_binder_callback_flush' before the end of the bulk initialization
05-23 18:47:45.748 E/YouTube (2733): InteractionLoggingScreen is null.
05-23 18:47:45.855 E/YouTube (2733): InteractionLoggingScreen is null.
05-23 18:47:46.180 E/YouTube (2733): InteractionLoggingScreen is null.
05-23 18:47:46.180 E/YouTube (2733): InteractionLoggingScreen is null.
05-23 18:47:46.190 W/YouTube (2733): Suppressed bad viewport dimensions. Video quality may suffer!
05-23 18:47:46.190 W/YouTube (2733): Suppressed bad viewport dimensions. Video quality may suffer!
05-23 18:47:46.226 E/YouTube (2733): InteractionLoggingScreen is null.
05-23 18:47:46.226 E/YouTube (2733): InteractionLoggingScreen is null.
05-23 18:47:46.509 W/Tesla.OEMBroadcast(28897): onReceive: android.intent.action.BADGE_COUNT_UPDATE ComponentTag{com.google.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity} 0
05-23 18:47:46.561 W/Tesla.OEMBroadcast(28897): onReceive: android.intent.action.BADGE_COUNT_UPDATE ComponentTag{com.google.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity} 0
05-23 18:47:47.382 E/AndroidRuntime(2733): Process: com.google.android.youtube, PID: 2733
05-23 18:47:47.382 E/AndroidRuntime(2733): 	at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback$HooksDownloadTask.doInBackground(YouTubeBackgroundPlayback.java:266)
05-23 18:47:47.382 E/AndroidRuntime(2733): 	at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback$HooksDownloadTask.doInBackground(YouTubeBackgroundPlayback.java:253)
05-23 18:47:47.386 W/ActivityManager(3982):   Force finishing activity com.google.android.youtube/com.google.android.apps.youtube.app.WatchWhileActivity
05-23 18:47:47.598 W/PkgUtils(28672): p: com.google.android.youtube, u:0
05-23 18:47:47.669 W/PkgUtils(29185): p: com.google.android.youtube, u:0
05-23 18:47:47.835 W/PkgUtils(28672): p: com.google.android.youtube, u:0
05-23 18:47:48.133 W/YouTube (2733): CsiAction [dfb] already ticked pl_int. Ignored.

**Comment by wanam** [comment]
It seems not related to my module, the crash starts with this module: com.pyler.youtubebackgroundplayback

**Comment by Sethur** [comment]
I checked my logcat and it appears that com.pyler.youtubebackgroundplayback caused the crashes as well with me.

**Comment by ChristophPech** [comment]
I might have a workaround for you: #94
Someone needs to make a test build. In theory it should crash once and then work.
